### ISSUE TITLE
Reload Causes Netlify Error in the "About Section"

### ISSUE THREAD

**Issue by beginner-cryptonyx** [Immortal-youtube/portfolioPersonal#1]
Upon Navigating to the about section and reloading, Netlify Raises the Following Error:
![image](https://user-images.githubusercontent.com/73869007/227697411-3438886d-d810-43c6-a800-c11a7cbfae96.png)
**Page Not Found**

**Comment by anshshrivastava0707** [comment]
Yes I am aware of that and will be working on fixing it.
